#####################################################################################
#####################################################################################
####   __   __  __   __  _______  _______   ___      _______  __    _  ______    ####
####  |  | |  ||  | |  ||       ||    _  | |   |    |   _   ||  |  | ||      |   ####
####  |  |_|  ||  |_|  ||    _  ||   | | | |   |    |  |_|  ||   |_| ||  _    |  ####
####  |       ||       ||   |_| ||   |_| |_|   |    |       ||       || | |   |  ####
####  |       ||_     _||    ___||    __  ||   |___ |       ||  _    || |_|   |  ####
####  |   _   |  |   |  |   |    |   |  | ||       ||   _   || | |   ||       |  ####
####  |__| |__|  |___|  |___|    |___|  |_||_______||__| |__||_|  |__||______|   ####
####                                                                             ####
#####################################################################################
#####################################################################################

$hyprPath = ~/.config/hypr/hyprland

# MONITORS
source = $hyprPath/monitor.conf

# PROGRAMS
source = $hyprPath/stdprogram.conf

# AUTOSTART
source = $hyprPath/autostart.conf

# ENVIRONMENT VARIABLES
source = $hyprPath/env.conf

# GENERAL
source = $hyprPath/general.conf

# DECORATION
source = $hyprPath/deco.conf

# ANIMATIONS
source = $hyprPath/animations.conf

# WINDOW RULES
source = $hyprPath/windowrules.conf

# INPUT
source = $hyprPath/input.conf

# KEYBINDS
source = $hyprPath/keybinds.conf
