#################
### AUTOSTART ###
#################

exec-once = hypridle & waybar & hyprpaper # launches lockscreen, idle manager, status bar and wallpaper
exec-once = systemctl --user start hyprpolkitagent # launches authentication agent
exec-once = mako # launches notification daemon
exec-once = filen sync ~/Documents:tw:Documents # syncs Documents folder using filen cli 
exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
