###############
### GENERAL ###
###############

general {
    border_size = 1
    gaps_in = 2 # gaps between windows
    gaps_out = 5 # gabs on edges
    col.active_border = rgb(d1d1d1)
    col.inactive_border = rgb(1c1c1c)
    resize_on_border = true # lets you resize your windows on their corner using your mouse
    layout = dwindle
}

dwindle {
    pseudotile = true
    preserve_split = true
}

misc {
    force_default_wallpaper = 1
    disable_hyprland_logo = true
}
