#############
### INPUT ###
#############

input {
    kb_layout = us
    kb_options = compose:ralt

    follow_mouse = 2 # will focus windows when clicked by mouse, not when hovered
    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
    natural_scroll = true

    touchpad {
    	scroll_factor = 0.4
        natural_scroll = true
    }
}

# GESTURES
gesture = 3, horizontal, workspace
