###################
### KEYBINDINGS ###
###################

# Keywords
$mainMod = SUPER
$shiftMod = SUPER + SHIFT


# 
bind = $mainMod, W, killactive,               # close window
bind = $mainMod, F, togglefloating,           # make window floating

# System Tools
bind = $mainMod,  SPACE, exec, $menu           # app menu
bind = $mainMod,  P,     exec, wlogout             # power menu
bind = $shiftMod, P,     exec, hyprshot -m region # screenshot of a region

# Binds for Apps
bind = $mainMod, RETURN, exec, $terminal      # terminal
bind = $mainMod, B,      exec, $browser       # browser
bind = $mainMod, O,      exec, obsidian       # obsidian
bind = $mainMod, M,      exec, $mailclient    # mail-client
bind = $mainMod, E,      exec, $fileManager   # file manager
bind = $mainMod, D,      exec, vesktop        # discord



### window behaviour ###

# moving windows
bind = $shiftMod, H, movewindow, l
bind = $shiftMod, J, movewindow, d
bind = $shiftMod, K, movewindow, u
bind = $shiftMod, L, movewindow, r

# resizing
binde = $mainMod, right, resizeactive, 10 0
binde = $mainMod, left, resizeactive, -10 0
bind = $mainMod, up, resizeactive, 0 -10
bind = $mainMod, down, resizeactive, 0 10

# Move focus
bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# Laptop multimedia keys for volume and LCD brightness
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-

# Requires playerctl
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous

# mouse binds
bindm = $mainMod, mouse:272, movewindow
