################
### MONITORS ###
################

monitor = eDP-1, 2880x1800@120, 0x0, 1.6 # build in monitor
monitor = desc:Samsung Electric Company SAMSUNG, preferred, auto-left, 1.07 # home monitor

monitor=,preferred, auto, auto
