###################
### MY PROGRAMS ###
###################

$terminal = ghostty
$fileManager = dolphin
$menu = ghostty --title="launcher" --confirm-close-surface=false -e ~/Repos/tux-launcher/tux
$browser = firefox
$mailclient = betterbird
